In [3]:
import pandas as pd

In [4]:
# Showcase ability to navigate through DataFrames using Loc/Iloc
# Filter and Slice DataFrames
# Create and access groupby objects
# How to Sort DataFrames

In [5]:
data = pd.read_csv('movies.csv')
data.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5

In [6]:
# Finding movies with greater than an IMDB rating of 7

print(data.loc[data['IMDB'] >= 7,['FILM','IMDB','IMDB_norm','IMDB_norm_round','IMDB_user_vote_count']].head())

                             FILM  IMDB  IMDB_norm  IMDB_norm_round  \
0  Avengers: Age of Ultron (2015)   7.8       3.90              4.0
1               Cinderella (2015)   7.1       3.55              3.5
2                  Ant-Man (2015)   7.8       3.90              4.0
5        The Water Diviner (2015)   7.2       3.60              3.5
8    Shaun the Sheep Movie (2015)   7.4       3.70              3.5

   IMDB_user_vote_count
0                271107
1                 65709
2                103660
5                 39373
8                 12227

In [7]:
# Movies with Less than 20k votes and Higher than a rating of 7

print(data.loc[(data['IMDB_user_vote_count']<20000) & (data['IMDB']>7),['FILM','IMDB','IMDB_user_vote_count']].head())

                                 FILM  IMDB  IMDB_user_vote_count
8        Shaun the Sheep Movie (2015)   7.4                 12227
9                 Love & Mercy (2015)   7.8                  5367
10  Far From The Madding Crowd (2015)   7.2                 12129
20              McFarland, USA (2015)   7.5                 13769
29         The End of the Tour (2015)   7.9                  1320

In [8]:
#Cleaning a Dataset

crime = pd.read_csv('crime.csv')
print(crime.count())

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
dtype: int64

In [9]:
crime = crime.dropna(how='any')
crime.count()

Address              36146
Case Number          36146
Crime Against        36146
Neighborhood         36146
Number of Records    36146
Occur Date           36146
Occur Month Year     36146
Occur Time           36146
Offense Category     36146
Offense Count        36146
Offense Type         36146
Open Data Lat        36146
Open Data Lon        36146
Open Data X          36146
Open Data Y          36146
Report Date          36146
Report Month Year    36146
dtype: int64

In [10]:
# Condensing Offense Type to Common Categories

print(crime['Offense Type'].unique())
crime['Offense Type'] = crime['Offense Type'].replace({'Identity Theft':'Theft','Credit Card/ATM Fraud':'Fraud',
                                                       'Shoplifting':'Theft','Theft From Motor Vehicle':'Theft',
                                                       'Motor Vehicle Theft':'Theft','Burglary':'Theft',
                                                       'Theft of Motor Vehicle Parts or Accessories':'Theft',
                                                       'Theft From Building':'Theft','Robbery':'Theft',
                                                       'Theft From Coin-Operated Machine or Device':'Theft',
                                                       'Pocket-Picking':'Theft','Stolen Property Offenses':'Theft',
                                                       'Purse-Snatching':'Theft', 'Wire Fraud':'Fraud','Welfare Fraud':'Fraud',
                                                      'Drug/Narcotic Violations':'Violations','Weapons Law Violations':'Violations',
                                                      'Drug Equipment Violations':'Violations','Counterfeiting/Forgery':'Fraud',
                                                      'Prostitution':'Sex Crimes','Pornography/Obscene Material':'Sex Crimes',
                                                      'Assisting or Promoting Prostitution':'Sex Crimes','Commercial Sex Acts':'Sex Crimes',
                                                      'Impersonation':'Fraud'})
print('--------------------------------------------------------------------------------------------')
print(crime['Offense Type'].unique())

['False Pretenses/Swindle/Confidence Game' 'Identity Theft'
 'Credit Card/ATM Fraud' 'Embezzlement' 'Shoplifting' 'All Other Larceny'
 'Theft From Motor Vehicle' 'Motor Vehicle Theft' 'Burglary'
 'Theft of Motor Vehicle Parts or Accessories' 'Counterfeiting/Forgery'
 'Vandalism' 'Theft From Building' 'Robbery' 'Aggravated Assault'
 'Theft From Coin-Operated Machine or Device' 'Intimidation'
 'Simple Assault' 'Hacking/Computer Invasion' 'Drug/Narcotic Violations'
 'Pocket-Picking' 'Stolen Property Offenses' 'Weapons Law Violations'
 'Purse-Snatching' 'Arson' 'Extortion/Blackmail' 'Prostitution'
 'Kidnapping/Abduction' 'Drug Equipment Violations'
 'Pornography/Obscene Material' 'Wire Fraud' 'Impersonation'
 'Assisting or Promoting Prostitution' 'Commercial Sex Acts'
 'Animal Cruelty' 'Welfare Fraud']
--------------------------------------------------------------------------------------------
['False Pretenses/Swindle/Confidence Game' 'Theft' 'Fraud' 'Embezzlement'
 'All Other Larceny' 'Vandalism' 'Aggravated Assault' 'Intimidation'
 'Simple Assault' 'Hacking/Computer Invasion' 'Violations' 'Arson'
 'Extortion/Blackmail' 'Sex Crimes' 'Kidnapping/Abduction'
 'Animal Cruelty']

In [11]:
# Creating a New Data Frame for a Specific Neighborhood

king_crime = crime.loc[crime['Neighborhood'] == 'King']
king_crime.head()

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
5,5400 BLOCK OF NE MALLORY AVE,17-900129,Property,King,1,11/28/2010,11/1/2010,1612,Fraud Offenses,1,Theft,45.5625,-122.664,7647987.0,698581.0,1/3/2017,1/1/2017
390,5500 BLOCK OF NE MARTIN LUTHER KING JR BLVD,17-9250,Property,King,1,12/10/2016,12/1/2016,0,Larceny Offenses,1,All Other Larceny,45.5631,-122.661,7648603.0,698786.0,1/10/2017,1/1/2017
611,900 BLOCK OF NE ALBERTA ST,17-900046,Property,King,1,1/1/2017,1/1/2017,925,Larceny Offenses,1,All Other Larceny,45.5592,-122.656,7649920.0,697323.0,1/2/2017,1/1/2017
708,NE 6TH AVE / NE BEECH ST,17-1842,Society,King,1,1/2/2017,1/1/2017,2144,Weapon Law Violations,1,Violations,45.5495,-122.660,7648922.0,693827.0,1/2/2017,1/1/2017
715,1400 BLOCK OF NE ALBERTA ST,17-900118,Property,King,1,1/1/2017,1/1/2017,1355,Vandalism,1,Vandalism,45.5591,-122.651,7651172.0,697285.0,1/3/2017,1/1/2017

In [25]:
# Using Group By

grouped = crime.groupby(['Offense Type'])
grouped.count().head(10)

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
Offense Type,,,,,,,,,,,,,,,,
Aggravated Assault,839,839,839,839,839,839,839,839,839,839,839,839,839,839,839,839
All Other Larceny,4558,4558,4558,4558,4558,4558,4558,4558,4558,4558,4558,4558,4558,4558,4558,4558
Animal Cruelty,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Arson,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200
Embezzlement,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73
Extortion/Blackmail,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
False Pretenses/Swindle/Confidence Game,870,870,870,870,870,870,870,870,870,870,870,870,870,870,870,870
Fraud,682,682,682,682,682,682,682,682,682,682,682,682,682,682,682,682
Hacking/Computer Invasion,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
Intimidation,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900

In [48]:
# Recap 

data = pd.read_csv('soccer_data.csv')
print(data.head(2))
print('------------------------------------------------')
print(data['Preferred Position'].unique())
print('------------------------------------------------')
st_players = data.loc[data['Preferred Position'] == 'ST']
print(st_players.head())

                Name  Age Nationality  Overall  Potential            Club  \
0  Cristiano Ronaldo   32    Portugal       94         94  Real Madrid CF
1           L. Messi   30   Argentina       93         93    FC Barcelona

  Preferred Position   CAM    CB   CDM  ...     RB   RCB   RCM   RDM    RF  \
0                 ST  89.0  53.0  62.0  ...   61.0  53.0  82.0  62.0  91.0
1                 RW  92.0  45.0  59.0  ...   57.0  45.0  84.0  59.0  92.0

     RM    RS    RW   RWB    ST
0  89.0  92.0  91.0  66.0  92.0
1  90.0  88.0  91.0  62.0  88.0

[2 rows x 33 columns]
------------------------------------------------
['ST' 'RW' 'LW' 'GK' 'CDM' 'CB' 'RM' 'CM' 'LM' 'LB' 'CAM' 'RB' 'CF' 'RWB'
 'LWB']
------------------------------------------------
                 Name  Age Nationality  Overall  Potential              Club  \
0   Cristiano Ronaldo   32    Portugal       94         94    Real Madrid CF
3           L. SuÃ¡rez   30     Uruguay       92         92      FC Barcelona
5      R. Lewandowski   28      Poland       91         91  FC Bayern Munich
9          G. HiguaÃ­n   29   Argentina       90         90          Juventus
16          S. AgÃ¼ero   29   Argentina       89         89   Manchester City

   Preferred Position   CAM    CB   CDM  ...     RB   RCB   RCM   RDM    RF  \
0                  ST  89.0  53.0  62.0  ...   61.0  53.0  82.0  62.0  91.0
3                  ST  87.0  58.0  65.0  ...   64.0  58.0  80.0  65.0  88.0
5                  ST  84.0  57.0  62.0  ...   58.0  57.0  78.0  62.0  87.0
9                  ST  81.0  46.0  52.0  ...   51.0  46.0  71.0  52.0  84.0
16                 ST  85.0  44.0  54.0  ...   52.0  44.0  75.0  54.0  87.0

      RM    RS    RW   RWB    ST
0   89.0  92.0  91.0  66.0  92.0
3   85.0  88.0  87.0  68.0  88.0
5   82.0  88.0  84.0  61.0  88.0
9   79.0  87.0  82.0  55.0  87.0
16  84.0  86.0  86.0  57.0  86.0

[5 rows x 33 columns]

In [54]:
# Sorting the Strikers by Striking Skill Score

st_players = st_players.sort_values('ST',ascending = False)
st_players.reset_index(drop=True)

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,ST,89.0,53.0,62.0,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,L. SuÃ¡rez,30,Uruguay,92,92,FC Barcelona,ST,87.0,58.0,65.0,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
2,R. Lewandowski,28,Poland,91,91,FC Bayern Munich,ST,84.0,57.0,62.0,...,58.0,57.0,78.0,62.0,87.0,82.0,88.0,84.0,61.0,88.0
3,G. HiguaÃ­n,29,Argentina,90,90,Juventus,ST,81.0,46.0,52.0,...,51.0,46.0,71.0,52.0,84.0,79.0,87.0,82.0,55.0,87.0
4,S. AgÃ¼ero,29,Argentina,89,89,Manchester City,ST,85.0,44.0,54.0,...,52.0,44.0,75.0,54.0,87.0,84.0,86.0,86.0,57.0,86.0
5,P. Aubameyang,28,Gabon,88,88,Borussia Dortmund,ST,82.0,52.0,59.0,...,62.0,52.0,74.0,59.0,84.0,83.0,85.0,84.0,65.0,85.0
6,Z. IbrahimoviÄ‡,35,Sweden,88,88,Manchester United,ST,83.0,52.0,60.0,...,54.0,52.0,78.0,60.0,83.0,80.0,84.0,82.0,58.0,84.0
7,E. Cavani,30,Uruguay,87,87,Paris Saint-Germain,ST,80.0,58.0,62.0,...,61.0,58.0,74.0,62.0,82.0,79.0,84.0,80.0,64.0,84.0
8,H. Kane,23,England,86,90,Tottenham Hotspur,ST,79.0,57.0,62.0,...,60.0,57.0,74.0,62.0,82.0,78.0,84.0,79.0,62.0,84.0
9,R. Lukaku,24,Belgium,86,90,Manchester United,ST,77.0,53.0,57.0,...,56.0,53.0,71.0,57.0,80.0,77.0,84.0,78.0,58.0,84.0
10,A. Lacazette,26,France,85,88,Arsenal,ST,81.0,54.0,60.0,...,59.0,54.0,74.0,60.0,83.0,80.0,83.0,82.0,62.0,83.0
11,T. MÃ¼ller,27,Germany,86,86,FC Bayern Munich,ST,81.0,58.0,65.0,...,66.0,58.0,78.0,65.0,83.0,81.0,83.0,81.0,68.0,83.0
12,P. Dybala,23,Argentina,88,93,Juventus,ST,86.0,43.0,55.0,...,55.0,43.0,78.0,55.0,86.0,86.0,83.0,87.0,60.0,83.0
13,Aduriz,36,Spain,84,84,Athletic Club de Bilbao,ST,76.0,60.0,58.0,...,58.0,60.0,69.0,58.0,80.0,73.0,83.0,75.0,58.0,83.0
14,K. Benzema,29,France,86,86,Real Madrid CF,ST,82.0,44.0,52.0,...,51.0,44.0,72.0,52.0,84.0,80.0,83.0,83.0,56.0,83.0
15,Diego Costa,28,Spain,86,86,Chelsea,ST,76.0,57.0,60.0,...,58.0,57.0,71.0,60.0,80.0,76.0,83.0,77.0,60.0,83.0
16,K. MbappÃ©,18,France,83,94,Paris Saint-Germain,ST,81.0,58.0,64.0,...,64.0,58.0,75.0,64.0,82.0,81.0,82.0,82.0,67.0,82.0
17,M. Icardi,24,Argentina,84,89,Inter,ST,75.0,46.0,50.0,...,49.0,46.0,67.0,50.0,79.0,73.0,82.0,75.0,51.0,82.0
18,Morata,24,Spain,84,88,Chelsea,ST,79.0,45.0,51.0,...,51.0,45.0,70.0,51.0,81.0,78.0,82.0,80.0,56.0,82.0
19,E. DÅ¾eko,31,Bosnia Herzegovina,84,84,Roma,ST,77.0,49.0,57.0,...,52.0,49.0,73.0,57.0,79.0,75.0,82.0,76.0,55.0,82.0
20,Falcao,31,Colombia,84,84,AS Monaco,ST,77.0,54.0,57.0,...,54.0,54.0,71.0,57.0,79.0,74.0,82.0,76.0,56.0,82.0
21,A. Belotti,23,Italy,83,90,Torino,ST,74.0,51.0,52.0,...,52.0,51.0,65.0,52.0,78.0,72.0,82.0,75.0,54.0,82.0
22,C. Immobile,27,Italy,82,83,Lazio,ST,75.0,54.0,56.0,...,56.0,54.0,67.0,56.0,79.0,74.0,81.0,76.0,58.0,81.0
23,B. Dost,28,Netherlands,83,83,Sporting CP,ST,71.0,57.0,57.0,...,54.0,57.0,67.0,57.0,76.0,68.0,81.0,69.0,55.0,81.0
24,A. Martial,21,France,82,90,Manchester United,ST,79.0,55.0,60.0,...,62.0,55.0,72.0,60.0,81.0,80.0,81.0,82.0,65.0,81.0
25,Willian JosÃ©,25,Brazil,82,86,Real Sociedad,ST,75.0,53.0,56.0,...,53.0,53.0,68.0,56.0,78.0,73.0,81.0,75.0,56.0,81.0
26,K. Gameiro,30,France,83,83,AtlÃ©tico Madrid,ST,80.0,51.0,59.0,...,59.0,51.0,74.0,59.0,81.0,80.0,81.0,80.0,62.0,81.0
27,T. Werner,21,Germany,82,87,RB Leipzig,ST,77.0,46.0,53.0,...,55.0,46.0,68.0,53.0,80.0,78.0,81.0,80.0,59.0,81.0
28,Lucas PÃ©rez,28,Spain,81,81,RC Deportivo de La CoruÃ±a,ST,79.0,49.0,57.0,...,55.0,49.0,73.0,57.0,80.0,79.0,80.0,80.0,59.0,80.0
29,I. Slimani,29,Algeria,82,82,Leicester City,ST,74.0,61.0,63.0,...,59.0,61.0,72.0,63.0,77.0,74.0,80.0,74.0,61.0,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,S. Kogut,20,Poland,50,59,Termalica Bruk-Bet Nieciecza,ST,44.0,32.0,31.0,...,32.0,32.0,38.0,31.0,46.0,44.0,49.0,45.0,34.0,49.0
2248,T. Knowles,18,England,50,71,Cambridge United,ST,46.0,33.0,33.0,...,34.0,33.0,40.0,33.0,48.0,45.0,49.0,46.0,35.0,49.0
2249,J. McMenemy,18,England,50,64,Lincoln City,ST,45.0,30.0,31.0,...,34.0,30.0,39.0,31.0,47.0,46.0,49.0,47.0,36.0,49.0
2250,A. Junge,24,Denmark,50,56,FC HelsingÃ¸r,ST,48.0,29.0,33.0,...,35.0,29.0,42.0,33.0,49.0,48.0,49.0,49.0,37.0,49.0
2251,S. Brady,21,Australia,53,64,Brisbane Roar,ST,53.0,40.0,43.0,...,46.0,40.0,49.0,43.0,52.0,53.0,49.0,53.0,46.0,49.0
2252,J. Earl,18,England,57,69,Preston North End,ST,49.0,51.0,51.0,...,56.0,51.0,49.0,51.0,50.0,53.0,49.0,52.0,56.0,49.0
2253,S. Nolan,17,Republic of Ireland,50,62,Bohemian FC,ST,49.0,33.0,36.0,...,39.0,33.0,44.0,36.0,50.0,50.0,49.0,50.0,40.0,49.0
2254,J. Johansson,18,Denmark,50,64,FC NordsjÃ¦lland,ST,47.0,30.0,32.0,...,32.0,30.0,41.0,32.0,48.0,46.0,49.0,47.0,34.0,49.0
2255,M. Moric,17,Australia,50,66,Newcastle Jets,ST,49.0,28.0,32.0,...,33.0,28.0,43.0,32.0,50.0,48.0,49.0,49.0,35.0,49.0
2256,A. Berisha,19,Sweden,50,65,Halmstads BK,ST,43.0,39.0,36.0,...,35.0,39.0,40.0,36.0,45.0,42.0,49.0,43.0,35.0,49.0
2257,A. Rose,18,Jamaica,50,60,Grimsby Town,ST,47.0,36.0,36.0,...,40.0,36.0,42.0,36.0,49.0,48.0,49.0,49.0,40.0,49.0
2258,C. Senior,20,England,55,67,Colchester United,ST,51.0,32.0,37.0,...,41.0,32.0,45.0,37.0,52.0,54.0,49.0,54.0,43.0,49.0
2259,G. Fasolo,18,Italy,50,65,Cittadella,ST,53.0,27.0,35.0,...,34.0,27.0,48.0,35.0,52.0,53.0,49.0,53.0,38.0,49.0
2260,A. Bruseth,18,Norway,50,62,Kristiansund BK,ST,46.0,29.0,29.0,...,32.0,29.0,39.0,29.0,48.0,46.0,49.0,48.0,33.0,49.0
2261,J. Aherne,18,Republic of Ireland,50,64,Bray Wanderers,ST,48.0,34.0,35.0,...,38.0,34.0,43.0,35.0,50.0,49.0,49.0,50.0,39.0,49.0
2262,J. Gray,19,Republic of Ireland,50,60,Stevenage,ST,47.0,27.0,29.0,...,31.0,27.0,39.0,29.0,48.0,46.0,49.0,48.0,32.0,49.0
2263,L. Demaj,19,Germany,50,64,SV Meppen,ST,49.0,27.0,31.0,...,34.0,27.0,42.0,31.0,50.0,49.0,49.0,51.0,36.0,49.0
2264,S. McSweeney,19,Republic of Ireland,49,59,Limerick FC,ST,48.0,29.0,34.0,...,34.0,29.0,45.0,34.0,48.0,48.0,48.0,48.0,36.0,48.0
2265,F. Roepstorff,19,Denmark,51,70,FC HelsingÃ¸r,ST,52.0,40.0,44.0,...,42.0,40.0,50.0,44.0,51.0,52.0,48.0,51.0,44.0,48.0
2266,R. Roache,17,Republic of Ireland,48,69,Blackpool,ST,43.0,27.0,29.0,...,31.0,27.0,38.0,29.0,45.0,43.0,47.0,44.0,32.0,47.0
2267,P. Almqvist,17,Sweden,51,68,IFK NorrkÃ¶ping,ST,51.0,43.0,47.0,...,48.0,43.0,50.0,47.0,50.0,52.0,47.0,51.0,48.0,47.0
2268,M. Warming,17,Denmark,51,66,BrÃ¸ndby IF,ST,50.0,36.0,40.0,...,40.0,36.0,47.0,40.0,49.0,50.0,47.0,50.0,42.0,47.0
2269,M. Foy,18,England,48,68,Cambridge United,ST,47.0,31.0,34.0,...,38.0,31.0,41.0,34.0,48.0,47.0,47.0,49.0,39.0,47.0
2270,H. Logan,18,England,53,72,Milton Keynes Dons,ST,52.0,38.0,43.0,...,43.0,38.0,50.0,43.0,50.0,52.0,47.0,51.0,44.0,47.0
2271,F. Prohart,18,Austria,47,67,Wolfsberger AC,ST,48.0,27.0,31.0,...,33.0,27.0,41.0,31.0,48.0,47.0,46.0,49.0,35.0,46.0
2272,J. Young,17,Scotland,46,61,Swindon Town,ST,44.0,28.0,29.0,...,31.0,28.0,38.0,29.0,45.0,42.0,45.0,44.0,32.0,45.0
2273,E. Mason-Clark,17,England,50,63,Barnet,ST,49.0,33.0,35.0,...,39.0,33.0,42.0,35.0,49.0,50.0,45.0,51.0,40.0,45.0
2274,O. Sowunmi,21,England,59,71,Yeovil Town,ST,35.0,58.0,47.0,...,52.0,58.0,37.0,47.0,38.0,38.0,44.0,37.0,49.0,44.0
2275,M. Zettl,18,Germany,50,67,SpVgg Unterhaching,ST,47.0,32.0,36.0,...,39.0,32.0,42.0,36.0,46.0,49.0,43.0,49.0,41.0,43.0
2276,L. Sackey,18,Ghana,46,64,Scunthorpe United,ST,29.0,45.0,38.0,...,40.0,45.0,30.0,38.0,29.0,30.0,31.0,29.0,38.0,31.0